name: diabetes-classifier-model-training
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - alembic==1.13.1
      - aniso8601==9.0.1
      - attrs==23.2.0
      - azure-ai-ml==1.16.1
      - azure-common==1.1.28
      - azure-core==1.30.1
      - azure-identity==1.16.0
      - azure-mgmt-core==1.4.0
      - azure-storage-blob==12.19.0
      - azure-storage-file-datalake==12.14.0
      - azure-storage-file-share==12.16.0
      - azureml-mlflow==1.56.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cryptography==42.0.7
      - cycler==0.12.1
      - deprecated==1.2.14
      - docker==7.1.0
      - entrypoints==0.4
      - flask==3.0.3
      - fonttools==4.52.4
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.19.0
      - google-auth==2.29.0
      - googleapis-common-protos==1.63.0
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - gunicorn==22.0.0
      - hyperopt==0.2.7
      - idna==3.7
      - importlib-metadata==7.0.0
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpickle==3.0.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - mako==1.3.5
      - markdown==3.6
      - markupsafe==2.1.5
      - marshmallow==3.21.2
      - matplotlib==3.9.0
      - mlflow==2.13.0
      - mlflow-skinny==2.13.0
      - msal==1.28.0
      - msal-extensions==1.1.0
      - msrest==0.7.1
      - networkx==3.3
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencensus-ext-azure==1.1.13
      - opencensus-ext-logging==0.1.1
      - opentelemetry-api==1.24.0
      - opentelemetry-sdk==1.24.0
      - opentelemetry-semantic-conventions==0.45b0
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - portalocker==2.8.2
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py4j==0.10.9.7
      - pyarrow==15.0.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydash==8.0.1
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - querystring-parser==1.2.4
      - referencing==0.35.1
      - requests==2.32.2
      - requests-oauthlib==2.0.0
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.16.0
      - smmap==5.0.1
      - sqlalchemy==2.0.30
      - sqlparse==0.5.0
      - strictyaml==1.7.3
      - threadpoolctl==3.5.0
      - tqdm==4.66.4
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xgboost==2.0.3
      - zipp==3.19.0
