name: diabetes-classifier-model
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - alembic==1.13.1
      - amqp==5.2.0
      - aniso8601==9.0.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - asyncssh==2.14.2
      - atpublic==4.1.0
      - attrs==23.2.0
      - azure-ai-ml==1.16.1
      - azure-common==1.1.28
      - azure-core==1.30.1
      - azure-identity==1.16.0
      - azure-mgmt-core==1.4.0
      - azure-storage-blob==12.19.0
      - azure-storage-file-datalake==12.15.0
      - azure-storage-file-share==12.16.0
      - azureml-mlflow==1.56.0
      - billiard==4.2.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - celery==5.4.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - comm==0.2.2
      - configobj==5.0.8
      - contourpy==1.2.1
      - cryptography==42.0.7
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - deprecated==1.2.14
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.6.1
      - docker==7.1.0
      - dpath==2.1.6
      - dulwich==0.22.1
      - dvc-data==3.15.1
      - dvc-http==2.32.0
      - dvc-objects==5.1.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.20.0
      - dvc-task==0.4.0
      - email-validator==2.1.1
      - entrypoints==0.4
      - executing==2.0.1
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filelock==3.14.0
      - flask==3.0.3
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - fonttools==4.52.4
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - funcy==2.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.19.0
      - google-auth==2.29.0
      - googleapis-common-protos==1.63.0
      - grandalf==0.8
      - graphene==3.3
      - graphql-core==3.2.3
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - gto==1.7.1
      - gunicorn==22.0.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - idna==3.7
      - importlib-metadata==7.0.0
      - ipykernel==6.29.4
      - ipython==8.24.0
      - isodate==0.6.1
      - iterative-telemetry==0.0.8
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpickle==3.0.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - kombu==5.3.7
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.2
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mlflow==2.13.0
      - mlflow-skinny==2.13.0
      - msal==1.28.0
      - msal-extensions==1.1.0
      - msrest==0.7.1
      - multidict==6.0.5
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.26.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencensus-ext-azure==1.1.13
      - opencensus-ext-logging==0.1.1
      - opentelemetry-api==1.24.0
      - opentelemetry-sdk==1.24.0
      - opentelemetry-semantic-conventions==0.45b0
      - orjson==3.10.3
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==3.11.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.45
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - pyarrow==15.0.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.7.2
      - pydantic-core==2.18.3
      - pydash==8.0.1
      - pydot==2.0.0
      - pygit2==1.15.0
      - pygments==2.18.0
      - pygtrie==2.5.0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - querystring-parser==1.2.4
      - referencing==0.35.1
      - requests==2.32.2
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - scmrepo==3.3.5
      - seaborn==0.13.2
      - semver==3.0.2
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.30
      - sqlparse==0.5.0
      - sqltrie==0.11.0
      - stack-data==0.6.3
      - starlette==0.37.2
      - strictyaml==1.7.3
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tomlkit==0.12.5
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typer==0.12.3
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.1
      - uvicorn==0.30.0
      - uvloop==0.19.0
      - vine==5.1.0
      - voluptuous==0.14.2
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xgboost==2.0.3
      - yarl==1.9.4
      - zc-lockfile==3.0.post1
      - zipp==3.19.0
