azure:
  AZURE_ML_SUBSCRIPTION_ID: 94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a
  AZURE_ML_RESOURCE_GROUP_NAME: 2024diabetesclassifier
  AZURE_ML_WORKSPACE_NAME: john-cummings-ml

  SERVICE_PRINCIPAL_TENANT_ID: e6ba44d9-c40a-4dc9-b59f-8fff330da1c0
  SERVICE_PRINCPAL_CLIENT_ID: f57439fb-8a1f-4eb4-a047-b9733b900a07

  BLOB_CONTAINER_NAME: 2024devdata