azure:
  AZURE_ML_SUBSCRIPTION_ID: 94f3bfe4-d65b-4af2-959a-f4cc3f4fef6a
  AZURE_ML_RESOURCE_GROUP_NAME: diabetes-classifier-2024
  AZURE_ML_WORKSPACE_NAME: diabetes-classifier-2024-dev

  AZURE_TENANT_ID: e6ba44d9-c40a-4dc9-b59f-8fff330da1c0
  AZURE_CLIENT_ID: efc9afe4-877c-4ccb-a264-2a0ee10b8c68

  BLOB_CONTAINER_NAME: 2024devdata

  AZURE_ML_TRAINING_ENV_NAME: diabetes_model_training_env

  AZURE_ML_TRAINING_COMPUTE_NAME: diabetes-training

  CONDA_TRAINING_ENV_FILE: diabetes_model/conda_training.yaml
  TRAINING_BASE_IMAGE: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  NUM_HYPEROPT_EVALS: "10"
  NUM_HYPEROPT_TRIALS_TO_LOG: "2"


