trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: |
    conda env create --quiet --file conda.yaml
  displayName: Create Anaconda environment

- bash: |
    source activate diabetes-classifier-model
    python -m cicd.upload_and_run_training_script
  displayName: Upload Data
  env:
    BLOB_CONNECTION_STRING: $(BLOB_CONNECTION_STRING)
    AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)